### ISSUE TITLE
Possible to change license to LGPL?

### ISSUE THREAD

**Issue by hobu** [1a7r0ch3/parallel-cut-pursuit#9]
I would like to lobby to change the license of this codebase to an LGPL variant (v2 or v3). We are the developers of [PDAL](https://github.com/PDAL/PDAL/) and many of our downstream users are embedding our software in commercial situations where GPLv3 is simply not going to be allowed due to the reciprocal nature of the license crossing their own code boundary. As such, we can't invest in bringing this algorithm to PDAL users except under some very specific circumstances.

An LGPL variant, however, could still maintain the reciprocation requirements of contribution of the PCP algorithm implementation. The PDAL team or its contributors are likely to help out in a few areas in support of bringing the capability to the PDAL toolkit. This includes library'ification of the PCP software, CMake build system support, and cross-platform C/C++ fixes. 

If this licensing change cannot work for you, we understand. While it would be nice, a BSD or MIT-style license is NOT NEEDED to satisfy our licensing challenges – LGPL will do. We are using LGPL with [LASzip](https://laszip.org/) quite widely and have seen good industry uptake, for example.

**Comment by 1a7r0ch3** [comment]
Hello

Thanks for your interest.

Although I would like to see more efforts put into keeping source code 
as free as possible, I understand that current state of things call for 
compromises, and I might consent to change the license to something less 
restrictive, so that the software touches a broader audience and gets 
more support.

However, the maximum flow solver I use is a derivative work of the 
academic release of Vladimir Kolmogorov's implementation (available at 
http://pub.ist.ac.at/~vnk/software.html), requiring a GPL (v2 or later) 
license.

I am not sure what the options are.

Maybe changing the maximum flow solver could be considered. I can 
provide support in that direction, but I do not have time to do it by 
myself. Actually I long wanted to change the graph structure used in 
this solver, reducing significantly the memory footprint of the method, 
but the way I intend to do it would still constitute a derivative work 
of Kolmogorov's source code.

Alternatively, maybe your library is modular enough so as to incorporate 
some functionalities with copyleft license. This is of course what I 
would prefer, though I understand that this would rule out some of your 
users, maybe up to the point that incorporating parallel cut pursuit to 
PDAL would not be worth it. However, if companies really need to hide 
their source code to make money, they might still consider buying a 
commercial license for Kolmogorov's work (see 
https://xip.uclb.com/i/software/optimisation_software/maxflow_computervision.html?redirected), 
and then get back to me. I have no idea how difficult would it be to do 
this in practice.

I remain open to any proposal.

Regards
Hugo Raguet

**Comment by hobu** [comment]
> However, the maximum flow solver I use is a derivative work of the academic release of Vladimir Kolomogov's implementation (available at http://pub.ist.ac.at/~vnk/software.html), requiring a GPL (v2 or later) license.

Ok, I didn't dig close enough to notice this. That will indeed limit the derivation to GPLv2 or later. 

> Alternatively, maybe your library is modular enough so as to incorporate some functionalities with copyleft license. This is of course what I would prefer, though I understand that this would rule out some of your users,

PDAL is very modular, including providing support for binary-only runtime-loaded plugins of functionality. This modularity will not overcome situations where the license constraints crosses the module boundary, like in the case of GPL. A binary-linked GPL-licensed PCP used in a PDAL runtime environment is not going to satisfy the licensing constraints of the GPL when mixed with any other completely closed software. This is what the GPL demands, of course, and this is author's choice to mandate too.

**Comment by hobu** [comment]
Given this discussion and the dependencies, let's close this issue for now. Maybe you can revisit if you change solvers or something.
